services:
  catalogue-app:
    image: docker.io/serhiyb86/catalogue:master
    container_name: catalogue-app
    expose:
      - 8080
      - 5005
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://localhost:5432/db-catalogue
      - QUARKUS_DATASOURCE_USERNAME=catalogue
      - QUARKUS_DATASOURCE_PASSWORD=Passw0rd!

