services:
  catalogue-app:
    image: docker.io/serhiyb86/catalogue:master
    container_name: catalogue-app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-catalogue:5432/db-catalogue
      QUARKUS_DATASOURCE_USERNAME: catalogue
      QUARKUS_DATASOURCE_PASSWORD: Passw0rd!
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create

