name: 'Build and publish docker image'
description: 'Build and publish docker image of archive with the name <version>-<ticket>-<type>'
inputs:
  image-tag:
    description: 'Image tag to set'
    required: true
  registry:
    description: "Account where the repository is located"
    required: true
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub username"
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Set up Java 21'
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Log in to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: 'Set up dependencies Buildx'
      uses: docker/setup-buildx-action@v3.3.0
      with:
        version: latest
        platforms: linux/amd64,linux/arm64
    - name: 'Build, tag, and push docker image to Docker Hub'
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        QUARKUS_DOCKER_BUILDX_PLATFORM: linux/amd64,linux/arm64
      run: |
        ./gradlew build -PdatabaseVendor=oracle -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=$REGISTRY \
          -Dquarkus.container-image.group=archive \
          -Dquarkus.container-image.name=archive \
          -Dquarkus.container-image.tag=$IMAGE_TAG \
          -x test -x quarkusIntTest -x testNative
