services:
  catalogue-app:
    image: docker.io/serhiyb86/catalogue:master
    container_name: catalogue-app
    expose:
      - 8080
      - 5005
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/db-catalogue
      - QUARKUS_DATASOURCE_USERNAME=catalogue
      - QUARKUS_DATASOURCE_PASSWORD=Passw0rd!
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:17
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalogue"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      - POSTGRES_USER=catalogue
      - POSTGRES_DB=db-catalogue
      - POSTGRES_PASSWORD=Passw0rd!
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
