services:
  catalogue-app:
    image: docker.io/serhiyb86/catalogue:master
    container_name: catalogue-app
    expose:
      - 8080
      - 5005
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=8080
    restart: always
    depends_on:
      db-catalogue:
        condition: service_healthy
  db-catalogue:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "archive" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      POSTGRES_USER: catalogue
      POSTGRES_DB: db-catalogue
      POSTGRES_PASSWORD: Passw0rd!

