services:
  catalogue-app:
    image: docker.io/serhiyb86/catalogue:first
    container_name: catalogue-app
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=8080
    restart: unless-stopped
    depends_on:
      - db-catalogue
  db-catalogue:
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: catalogue
      POSTGRES_DB: db-catalogue
      POSTGRES_PASSWORD: Passw0rd!

