services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
