name: Build
on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore: [ 'doc/**' ]
  push:
    branches: [ 'main', 'master', 'release/**', 'bugfix/**', 'documentation/**' ]
    paths-ignore: [ 'doc/**' ]
jobs:
  unit-test:
    name: "Backend Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up Java 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set execute permissions for gradlew
        shell: bash
        run: chmod +x ./gradlew
      - name: Run tests
        shell: bash
        run: |
          echo "Hello world" 
          ./gradlew test 
          ls
  # Build and push docker image
  docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs:
      - unit-test
#      - start-analysis-runner
#      - sonar
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout Code'
        with:
          fetch-depth: 0
      - name: 'Define image tag'
        shell: bash
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          TAG=$(.github/tools/get-image-tag.sh "$HEAD_REF")
          echo "TAG=$TAG" >> "$GITHUB_ENV"
          echo "TAG=$TAG"
      - uses: ./.github/action/build-docker
        name: 'Build and push docker image'
        with:
          image-tag: ${{ env.TAG }}
          registry: docker.io

